### ISSUE TITLE
Error in console 

### ISSUE THREAD

**Issue by sparcoxalpha** [Micky014/FiveM-Manifest-Converter#1]
After converting , when server starts, showing many errors sql

**Comment by Micky014** [comment]
Try reinstalling the SQL library you use.

**Comment by Micky014** [comment]
[Read this](https://github.com/Micky014/FiveM-Manifest-Converter/commit/111fa005c8b6ac49fe092f57e4fed925ce76a86e#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
